### ISSUE TITLE
Asking for help with Multivariate time series data

### ISSUE THREAD

**Issue by khaled-alkilane** [hamrel-cxu/SPCI-code#1]
First, thanks for the interesting work. I am trying to apply the SPCI on a multivariate time series dataset (where there are correlations between between records from different sensors in the network). I give a small sample example of the data in the table below. Actually, what I am trying to do is to find the prediction intervals for multiple sensors in the next hour considering the previous historical one hour. I am wondering if this is applicable using SPCI. Any help or comment would be appreciated.

Timestamp                   |   Sensor1  |   sensor2  |  ...  | sensor(n) |
--------------------------------------------------------------
2019-01-1 00:00:00   |     20         |       120      | ...   |    404       |
2019-01-1 00:15:00    |     211        |       12        | ...   |    1305      |
2019-01-1 00:30:00   |     1470     |       477     | ...    |    41          |
.
.
.
2019-01-25 23:45:00   |    3         |      200      |   ...   |      12       |
--------------------------------------------------------------

**Comment by hamrel-cxu** [comment]
Thank you for your interest in our work. What you described is essentially producing multivariate prediction *region* for $Y\in \mathbb{R}^n$. You can definitely use our SPCI to calibrate the quantile of some non-conformity score, which is likely NOT going to be the prediction residual, because it is high-dimensional.

In fact, we are currently developing a multi-variate version of SPCI, so stay tuned. In the meantime, this work https://arxiv.org/abs/2101.12002 may be of interest to you, although it is not for time-series.

**Comment by khaled-alkilane** [comment]
Thank you. Looking forward for the release of the multi-variate version of SPCI.
